x-common-config: &common-config
  build:
    context: .
    dockerfile: Dockerfile
  volumes:
    - ./config.json:/app/config.json
    - ./googleconfig.json:/app/googleconfig.json
    - ./data:/app/data
    - ./sessions:/app/sessions
    - ./state:/app/state
    - ./memory:/app/memory
    - ./secrets:/app/secrets
    - ./whatsapp-auth:/app/whatsapp-auth
    - ./whatsapp-web:/app/whatsapp-web
    - ./whatsapp-web-debug:/app/whatsapp-web-debug
    - ./skills:/app/skills

services:
  nanobot-gateway:
    container_name: nanobot-gateway
    <<: *common-config
    command: ["gateway"]
    restart: unless-stopped
    ports:
      - 18790:18790
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.25'
          memory: 256M
  
  nanobot-cli:
    <<: *common-config
    profiles:
      - cli
    command: ["status"]
    stdin_open: true
    tty: true
